(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'df' is not defined"
p3
sS'layer'
p4
S'C:\\Work\\web2py\\applications\\bootcamp_template\\controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 000000000A22A9B0, file "C:\\Work\\web2py\\applications\\bootcamp_template\\controllers/default.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Work\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Work\\web2py\\applications\\bootcamp_template\\controllers/default.py", line 79, in <module>\n  File "C:\\Work\\web2py\\gluon\\globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Work\\web2py\\applications\\bootcamp_template\\controllers/default.py", line 25, in get_data\n    for i, row in df.iterrows():\nNameError: global name \'df\' is not defined\n'
p11
s.